# Generated by Django 3.2.15 on 2022-11-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='uploads/profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile.jpg', upload_to='uploads/profile/compressed/'),
        ),
    ]
